name: flutter_image_clip_example
description: Example app for flutter_image_clip.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_image_clip:
    path: ..
  image_picker: ^1.2.2

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
