name: flutter_image_clip
description: A reusable Android and iOS Flutter image clipping library with a ready-to-use crop editor UI and image processing APIs.
version: 0.6.1
repository: https://github.com/LJMcarryu/flutter_image_clip

topics:
  - image
  - crop
  - clipping
  - editor

platforms:
  android:
  ios:

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  image: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  image_picker: ^1.2.2

flutter:
  uses-material-design: true
